{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntestallur_demo.py:10: AssertionError"}, "description": "this test fails", "start": 1624886391334, "stop": 1624886391334, "uuid": "da00dfea-8dbc-4727-ac43-ff5f7d082bed", "historyId": "21f8b0f332a3f77c1e3f0dfcc212df1e", "testCaseId": "f95a7898c168baa45d5d740f64ed8445", "fullName": "testallur_demo#test_failure", "labels": [{"name": "suite", "value": "testallur_demo"}, {"name": "host", "value": "LAPTOP-59S4SB4A"}, {"name": "thread", "value": "22296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testallur_demo"}]}